### ISSUE TITLE
Upload images have different size limit to browser

### ISSUE THREAD

**Issue by Ruriko** [Pyprohly/reddit-api-doc-notes#2]
So I'm trying to upload a 3mb image using POST to /api/media/asset but it seems that it has a size limit of 500kb but that doesn't seem correct cause if you create the image post using a browser you can upload up to 20mb.
`parent.completedUploadImage('failed','','',[['BAD_CSS_NAME', ''], ['IMAGE_ERROR', 'too big. keep it under 500 KiB']],'');you shouldn't be here`

I'm just wondering if there are any settings that need to be configured or I have the wrong endpoint to upload images?

**Comment by Pyprohly** [comment]
I can upload images up to 20 MiB. Could you give more details about the upload process you're using?
